apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1ete
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-azcx-tenant/rhtap-demo-app/hacbs-test-project-1ete@sha256:cd457bf3c2ee8e64eabf63e6acc3b723fb33bb774fe10495e82ff209033adaec
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
