apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1ete
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1ete
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1ete
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1ete
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1ete
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-azcx-tenant/rhtap-demo-app/hacbs-test-project-1ete@sha256:e6fb80e55be73c4c154e6642b7273861565cd8e8c4e7f6f8eb0d01510b519ca6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
